const { Telegraf, Markup } = require("telegraf")
require("dotenv").config()
const bot = new Telegraf(process.env.BOT_TOKEN)
bot.start((ctx) => ctx.reply('Чтобы начать, нам необходимо настроить категории поиска. Не переживайте - их можно перенастроить в любой момент. После выбора категории поиска бот начнет отслеживать релевантные предложения и высылать их в этот чат. Это может занять некоторое время - в зависимости от появления новых запросов, подходящих под ваши критерии поиска. Ну что, приступим?'))
bot.help((ctx) => ctx.reply('Обратитесь в службу поддержки'))
// bot.on('sticker', (ctx) => ctx.reply('Like'))
// bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.launch()
process.once('SIGINT', () => bot.stop('SIGINT'))
process.once('SIGTERM', () => bot.stop('SIGTERM'))